require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5.6
  Exclude:
    - db/schema.rb
Metrics/LineLength:
  Max: 100
Documentation:
  Enabled: false
Rails:
  Enabled: true