# require:
#   - rubocop-md
#   - rubocop-performance
#   - rubocop-rails
#   - rubocop-rake
#   - rubocop-rspec

# AllCops:
#   DisplayCopNames: true
#   DisplayStyleGuide: true
#   TargetRubyVersion: 2.6.5
#   Exclude:
#     - db/schema.rb
# Metrics/LineLength:
#   Max: 100
# Style/Documentation:
#   Enabled: false
# Rails:
#   Enabled: true