tap "caskroom/cask"
tap "caskroom/drivers"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/versions"
tap "joshuaclayton/formulae"
tap "michaeldfallen/formula"
brew "autoconf"
brew "bash"
brew "bash-completion@2"
brew "brew-pip"
brew "ghc"
brew "cabal-install"
brew "chromedriver", restart_service: true
brew "coreutils"
brew "ctags"
brew "diff-so-fancy"
brew "jpeg"
brew "libpng"
brew "libtiff"
brew "wxmac"
brew "erlang"
brew "elixir"
brew "gdbm"
brew "git"
brew "gnupg"
brew "sqlite"
brew "xz"
brew "python3"
brew "httpie"
brew "hub"
brew "jq"
brew "libxml2"
brew "libyaml"
brew "mas"
brew "mongodb", restart_service: true
brew "mysql"
brew "openssl@1.1"
brew "pcre"
brew "nginx", restart_service: true
brew "nvm"
brew "pkg-config"
brew "postgresql", restart_service: true
brew "rabbitmq", restart_service: true
brew "ruby-build"
brew "rbenv"
brew "redis", restart_service: true
brew "ruby"
brew "shellcheck"
brew "the_silver_searcher"
brew "webkit2png"
brew "wget"
brew "wifi-password"
brew "yarn"
brew "joshuaclayton/formulae/unused"
brew "michaeldfallen/formula/git-radar"
cask "appcleaner"
cask "choosy"
cask "coconutbattery"
cask "commandq"
cask "disk-inventory-x"
cask "divvy"
cask "dropbox"
cask "duet"
cask "firefox"
cask "fman"
cask "garmin-express"
cask "gimp"
cask "google-chrome"
cask "image2icon"
cask "iterm2"
cask "keka"
cask "keybase"
cask "libreoffice"
cask "postman"
cask "psequel"
cask "robomongo"
cask "sequel-pro"
cask "skype"
cask "slack"
cask "smcfancontrol"
cask "spotify"
cask "sublime-text"
cask "subtitles"
cask "telegram"
cask "trailer"
cask "transmission"
cask "vlc"
cask "xscope"
mas "FreeMemory Pro", id: 486967844
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Proxie", id: 897814548
