tap "caskformula/caskformula"
tap "caskroom/cask"
tap "caskroom/drivers"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/versions"
tap "joshuaclayton/formulae"
tap "michaeldfallen/formula"
brew "pcre"
brew "git"
brew "pkg-config"
brew "autoconf"
brew "bash"
brew "bash-completion@2"
brew "brew-pip"
brew "ghc"
brew "cabal-install"
brew "ccat"
brew "chromedriver", restart_service: true
brew "coreutils"
brew "ctags"
brew "diff-so-fancy"
brew "openssl"
brew "wxmac"
brew "erlang"
brew "ffmpeg"
brew "libxml2"
brew "sqlite"
brew "mysql"
brew "gdbm"
brew "xz"
brew "python3"
brew "postgresql", restart_service: true
brew "gifsicle"
brew "gnupg"
brew "gnupg@1.4"
brew "graphviz"
brew "httpie"
brew "hub"
brew "imagemagick"
brew "jq"
brew "libyaml"
brew "makedepend"
brew "mas"
brew "mongodb"
brew "nginx"
brew "nvm"
brew "openssl@1.1"
brew "phantomjs"
brew "rabbitmq"
brew "ruby-build"
brew "rbenv"
brew "redis"
brew "ruby"
brew "shellcheck"
brew "the_silver_searcher"
brew "webkit2png"
brew "wget"
brew "wifi-password"
brew "yarn"
brew "youtube-dl"
brew "joshuaclayton/formulae/unused"
brew "michaeldfallen/formula/git-radar"
cask "appcleaner"
cask "caprine"
cask "caption"
cask "charles"
cask "choosy"
cask "chromium"
cask "coconutbattery"
cask "commandq"
cask "disk-inventory-x"
cask "divvy"
cask "dropbox"
cask "duet"
cask "firefox"
cask "fman"
cask "gimp"
cask "gitter"
cask "google-chrome"
cask "iina"
cask "image2icon"
cask "iterm2"
cask "keka"
cask "keybase"
cask "libreoffice"
cask "licecap"
cask "postman"
cask "psequel"
cask "sequel-pro"
cask "skype"
cask "slack"
cask "spotify"
cask "sublime-text"
cask "telegram"
cask "trailer"
cask "transmission"
cask "xscope"
cask "caskroom/drivers/garmin-express"
cask "caskroom/fonts/font-hack"
cask "caskroom/versions/google-chrome-canary"
mas "Battery Indicator", id: 1206020918
mas "FreeMemory Pro", id: 486967844
mas "iMovie", id: 408981434
mas "Install macOS High Sierra", id: 0
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Proxie", id: 897814548
mas "WhatsApp", id: 1147396723
