tap "caskformula/caskformula"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "homebrew/services"
tap "joshuaclayton/formulae"
tap "michaeldfallen/formula"
brew "autoconf"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "brew-pip"
brew "ghc"
brew "cabal-install"
brew "openssl"
brew "readline"
brew "ccat"
brew "coreutils"
brew "ctags"
brew "diff-so-fancy"
brew "elasticsearch@5.6", restart_service: true, link: true
brew "ffmpeg"
brew "fzf"
brew "git"
brew "gnupg"
brew "gnupg@1.4"
brew "graphviz"
brew "htop"
brew "httpie"
brew "hub"
brew "imagemagick@6", link: true
brew "jq"
brew "libxml2"
brew "lighttpd"
brew "makedepend"
brew "mas"
brew "mysql@5.7", restart_service: true, link: true
brew "newsboat"
brew "nginx"
brew "pkg-config"
brew "postgresql"
brew "psgrep"
brew "pv"
brew "ruby-build"
brew "rbenv"
brew "rbenv-default-gems"
brew "rbenv-gemset"
brew "rbenv-vars"
brew "redis", restart_service: true
brew "s3cmd"
brew "shellcheck"
brew "task"
brew "the_silver_searcher"
brew "tldr"
brew "translate-shell"
brew "webkit2png"
brew "wget"
brew "wifi-password"
brew "wxmac"
brew "youtube-dl"
brew "joshuaclayton/formulae/unused"
brew "michaeldfallen/formula/git-radar"
cask "appcleaner"
cask "bose-updater"
cask "caption"
cask "choosy"
cask "chromedriver"
cask "chromium"
cask "coconutbattery"
cask "commandq"
cask "digikam"
cask "disk-inventory-x"
cask "divvy"
cask "dropbox"
cask "filezilla"
cask "firefox"
cask "font-hack"
cask "garmin-express"
cask "garmin-virb-edit"
cask "gimp"
cask "google-chrome"
cask "google-chrome-canary"
cask "grammarly"
cask "iina"
cask "image2icon"
cask "iterm2"
cask "java8"
cask "kap"
cask "keka"
cask "libreoffice"
cask "mactracker"
cask "postman"
cask "qutebrowser"
cask "sequel-pro"
cask "slack"
cask "spotify"
cask "steam"
cask "sublime-text"
cask "telegram"
cask "trainerroad"
cask "transmission"
cask "virtualbox"
cask "xscope"
cask "zwift"
mas "com.apple.iMovieApp", id: 408981434
mas "com.apple.iWork.Keynote", id: 409183694
mas "com.apple.iWork.Numbers", id: 409203825
mas "com.apple.iWork.Pages", id: 409201541
mas "com.helloresolven.GIF-Brewery-3", id: 1081413713
mas "com.rockysandstudio.FreeMemory-Pro", id: 486967844
mas "com.sindresorhus.Battery-Indicator", id: 1206020918
mas "desktop.WhatsApp", id: 1147396723
mas "us.patr0n.cellist", id: 897814548
