tap "buo/cask-upgrade"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "homebrew/services"
tap "michaeldfallen/formula"
tap "unused-code/formulae"
# Automatic configure script builder
brew "autoconf"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Programmable completion for Bash 4.2+
brew "bash-completion@2"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Install pip packages as homebrew formulae
brew "brew-pip"
# Glorious Glasgow Haskell Compilation System
brew "ghc"
# Command-line interface for Cabal and Hackage
brew "cabal-install"
# Library for command-line editing
brew "readline"
# Command-line interface for SQLite
brew "sqlite"
# Like cat but displays content with syntax highlighting
brew "ccat"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Reimplementation of ctags(1)
brew "ctags"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Good-lookin' diffs with diff-highlight and more
brew "diff-so-fancy"
# Manage compile and link flags for libraries
brew "pkg-config"
# Validating, recursive, caching DNS resolver
brew "unbound"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Command-line fuzzy finder written in Go
brew "fzf"
# Distributed revision control system
brew "git"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Improved top (interactive process viewer)
brew "htop"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Add GitHub support to git on the command-line
brew "hub"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# International domain name library
brew "libidn"
# GNOME XML library
brew "libxml2"
# Small memory footprint, flexible web-server
brew "lighttpd"
# Creates dependencies in makefiles
brew "makedepend"
# NCurses Disk Usage
brew "ncdu"
# Fast, highly customisable system info script
brew "neofetch"
# HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
brew "nginx"
# Object-relational database system
brew "postgresql"
# Install various Ruby versions and implementations
brew "ruby-build"
# Ruby version manager
brew "rbenv"
# Auto-installs gems for Ruby installs
brew "rbenv-default-gems"
# Adds basic gemset support to rbenv
brew "rbenv-gemset"
# Safely sets global and per-project environment variables
brew "rbenv-vars"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Code-search similar to ack
brew "the_silver_searcher"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# Command-line translator using Google Translate and more
brew "translate-shell"
# Create screenshots of webpages from the terminal
brew "webkit2png"
# Internet file retriever
brew "wget"
# Show the current WiFi network password
brew "wifi-password"
# Cross-platform C++ GUI toolkit (wxWidgets for macOS)
brew "wxmac"
# Download YouTube videos from the command-line
brew "youtube-dl"
# Everything you need to get started with Heroku
brew "heroku/brew/heroku"
brew "michaeldfallen/formula/git-radar"
cask "adobe-air-beta"
# Application uninstaller
cask "appcleaner"
# Software updates for Bose products
cask "bose-updater"
# Finds and sets up subtitles automatically
cask "caption"
# Open links in any browser
cask "choosy"
# Automated testing of webapps for Google Chrome
cask "chromedriver"
# Free and open-source web browser
cask "chromium"
# Tool to show live information about the batteries in various devices
cask "coconutbattery"
# Allows switching between application windows
cask "contexts"
# Trains AIs to understand and translate texts
cask "deepl"
cask "digikam"
# Application window manager focusing on simplicity
cask "divvy"
# Client for the Dropbox cloud storage service
cask "dropbox"
cask "filezilla"
# Web browser
cask "firefox"
# Screen color temperature controller
cask "flux"
cask "font-hack"
cask "garmin-express"
# Free and open-source image editor
cask "gimp"
# Web browser
cask "google-chrome"
# Web browser
cask "google-chrome-canary"
# Utility to fix grammar errors and style issues in text
cask "grammarly"
# Open-source video transcoder
cask "handbrake"
# Free and open-source media player
cask "iina"
# Icon creator and file and folder customizer
cask "image2icon"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Open-source screen recorder built with web technology
cask "kap"
# File archiver
cask "keka"
# GPU-based terminal emulator
cask "kitty"
# Password manager
cask "lastpass"
# Office suite
cask "libreoffice"
# Detailed information on every Apple product ever made
cask "mactracker"
# Geographic Information System
cask "qgis"
# Keyboard-driven, vim-like browser based on PyQt5
cask "qutebrowser"
cask "screen"
# MySQL/MariaDB database management platform
cask "sequel-pro"
# Instant messaging application focusing on security
cask "signal"
# Video chat, voice call and instant messaging application
cask "skype"
# Team communication and collaboration software
cask "slack"
# Sound and audio controller
cask "soundsource"
# Music streaming service
cask "spotify"
# Text editor for code, markup and prose
cask "sublime-text"
# Messaging app with a focus on speed and security
cask "telegram"
# Open-source BitTorrent client
cask "transmission"
# Free and open-source hosted hypervisor for x86 virtualization
cask "virtualbox"
# Tools for measuring, inspecting & testing on-screen graphics and layouts
cask "xscope"
# Video communication and virtual meeting platform
cask "zoom"
