tap "buo/cask-upgrade"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/command-not-found"
tap "homebrew/services"
tap "michaeldfallen/formula"
tap "unused-code/formulae"
tap "yukiarrr/tap"
# Color management engine supporting ICC profiles
brew "little-cms2"
# Image format providing lossless and lossy compression for web images
brew "webp"
# New file format for still image compression
brew "jpeg-xl"
# Codec library for encoding and decoding AV1 video streams
brew "aom"
# Mozilla CA certificate store
brew "ca-certificates"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Official Amazon AWS command-line interface
brew "awscli"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Programmable completion for Bash 4.2+
brew "bash-completion@2"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Glorious Glasgow Haskell Compilation System
brew "ghc"
# Command-line interface for Cabal and Hackage
brew "cabal-install"
# Core application library for C
brew "glib"
# Like cat but displays content with syntax highlighting
brew "ccat"
# Cross-platform make
brew "cmake"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Reimplementation of ctags(1)
brew "ctags"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Good-lookin' diffs with diff-highlight and more
brew "diff-so-fancy"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# C/C++ and Java libraries for Unicode and globalization
brew "icu4c@76"
# OpenType text shaping engine
brew "harfbuzz"
# Image processing and image analysis library
brew "leptonica"
# Framework for layout and rendering of i18n text
brew "pango"
# Secure Reliable Transport
brew "srt"
# OCR (Optical Character Recognition) engine
brew "tesseract"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Command-line fuzzy finder written in Go
brew "fzf"
# Graphics library to dynamically manipulate images
brew "gd"
# Toolkit for image loading and pixel buffer manipulation
brew "gdk-pixbuf"
# International domain name library
brew "libidn"
# Interpreter for PostScript and PDF
brew "ghostscript"
# Distributed revision control system
brew "git"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Manage compile and link flags for libraries
brew "pkg-config"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# Image manipulation
brew "netpbm"
# Library to render SVG files using Cairo
brew "librsvg"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Improved top (interactive process viewer)
brew "htop"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Add GitHub support to git on the command-line
brew "hub"
# Tools and libraries to manipulate images in many formats
brew "imagemagick@6"
# Lightweight and flexible command-line JSON processor
brew "jq"
# ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
brew "libheif"
# C library for the MaxMind DB file format
brew "libmaxminddb"
# Postgres C API library
brew "libpq"
# Library for reading RAW files from digital photo cameras
brew "libraw"
# GNOME XML library
brew "libxml2"
# YAML Parser
brew "libyaml"
# Open source suite of directory software
brew "openldap"
# Small memory footprint, flexible web-server
brew "lighttpd"
# Creates dependencies in makefiles
brew "makedepend"
# NCurses Disk Usage
brew "ncdu"
# HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
brew "nginx"
# Install various Ruby versions and implementations
brew "ruby-build"
# Ruby version manager
brew "rbenv"
# Auto-installs gems for Ruby installs
brew "rbenv-default-gems"
# Adds basic gemset support to rbenv
brew "rbenv-gemset"
# Safely sets global and per-project environment variables
brew "rbenv-vars"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Code-search similar to ack
brew "the_silver_searcher"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# Command-line translator using Google Translate and more
brew "translate-shell"
# Create screenshots of webpages from the terminal
brew "webkit2png"
# Internet file retriever
brew "wget"
# Show the current WiFi network password
brew "wifi-password"
# Cross-platform C++ GUI toolkit
brew "wxwidgets"
# JavaScript package manager
brew "yarn"
# Everything you need to get started with Heroku
brew "heroku/brew/heroku"
brew "michaeldfallen/formula/git-radar"
# ecsk is a CLI tool to interactively use frequently used functions of docker command in Amazon ECS. (docker run, exec, cp, logs, stop)
brew "yukiarrr/tap/ecsk"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Application uninstaller
cask "appcleaner"
# Automated testing of webapps for Google Chrome
cask "chromedriver"
# Allows switching between application windows
cask "contexts"
# Voice and text chat software
cask "discord"
# Application window manager focusing on simplicity
cask "divvy"
# App to build and share containerised applications and microservices
cask "docker"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Web browser
cask "firefox"
cask "font-hack"
# Free and open-source image editor
cask "gimp"
# Web browser
cask "google-chrome"
# Free and open-source media player
cask "iina"
# Vector graphics editor
cask "inkscape"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# File archiver
cask "keka"
# Free cross-platform office suite, fresh version
cask "libreoffice"
# Provides access to camera controls
cask "logitech-camera-settings"
# Detailed information on every Apple product ever made
cask "mactracker"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# Simple application that will prevent iTunes or Apple Music from launching
cask "notunes"
# Plugin for AWS CLI to start and end sessions that connect to managed instances
cask "session-manager-plugin"
# Team communication and collaboration software
cask "slack"
# Sound and audio controller
cask "soundsource"
# Music streaming service
cask "spotify"
# Video game digital distribution service
cask "steam"
# Text editor for code, markup and prose
cask "sublime-text"
# Messaging app with a focus on speed and security
cask "telegram"
# Open-source BitTorrent client
cask "transmission"
# Video communication and virtual meeting platform
cask "zoom"
