#!/usr/bin/env bash

# Bash
alias c='bat'
alias cat='bat'
alias ll='gls -GlAhp --group-directories-first --color=auto'
alias reload='source ~/.bash_profile'
alias f='open -a Finder ./' # Opens current directory with macos Finder
alias rmrf='rm -rf'
alias ..="cd .."
alias -- -="cd -"

# Shortcuts
alias dl="cd ~/Downloads"

# Git
alias g='git'
alias gemc='git_edit_merge_conflicts'
alias galias='git config --get-regexp alias'
## Commiting
alias ga='git ga'
alias gaa='git gaa'
alias gai='git gai'
alias gc='git commit'
alias gcm='git commit -m'
alias gcmn='git commit --no-verify -m'
## Github
alias PR='git PR'
alias PRO='~./dotfiles/github-pull-request'
## History
alias gl='git gl -20'
alias gla='git gl'
alias gll='git log'
alias glf='git glf'
alias up='git up'
## Maintenance
alias cleanup='clearb;rpo;ggc'
alias clearb='git clearb'
alias ggc='git gc --auto'
alias rpo='git rpo'
alias ggca='git gc --aggressive'
## Pushing & Pulling
alias p='git p'
alias P='git push'
alias PU='git pu'
alias PUF='git pu --force-with-lease'
## Status
alias cgs='clear; git st' # Clear screen and git status
alias gd='git gd'
alias gdf='git gdf'
alias gds='git gds'
alias gdsf='git gdsf'
alias gs='git st'

# Ruby
alias r='ruby'
## Rubocoping
alias fix_ruby="grep -E 'rb|rake|Gemfile|ru' | xargs rubocop -A --parallel"
alias ru='git gsp | fix_ruby' # autocorrect ruby files listed on working directory & staging area
alias rum='git gdmaster | fix_ruby' # autocorrect ruby files in diff between current branch and master
alias solocop='bundle exec rubocop --parallel --only' # autocorrect using a single cop by name (passed as argument)
alias bra='bundle exec rubocop -A'
alias brao='bra --only'
alias bre='bundle exec rubocop'
alias bres='bre --display-only-safe-correctable'
# Bundle
alias b='bundle'
alias be='b exec'
alias ber='bundle exec bin/rake'
alias bus='bundle update --source'
## RSpec
alias sp='bundle exec rspec --order rand'
alias spf='sp --fail-fast'
alias spd='sp --format documentation'
alias spt='sp --tag'
alias spc='sp --color --format documentation --require spec_helper --require rails_helper spec'
alias sps='sp --seed'
alias sph='HEADLESS=false sp'
alias spm='sp `git ls-files -m \*_spec.rb`'
## Rails
alias rc='rails c'
alias rs='rails s'
alias rg='rails generate'
alias dbmigrate='ber db:migrate RAILS_ENV=development; ber db:migrate RAILS_ENV=test'
alias dbrollback='ber db:rollback RAILS_ENV=development; ber db:rollback RAILS_ENV=test'
alias dbreset='ber db:drop; ber db:create; dbmigrate; ber db:seed'
alias routes='bundle exec rails routes | fzf'
## Jekyll
alias js='bundle exec jekyll serve --watch'
alias serve="ruby -run -ehttpd" # serves the current directory up on port 8080 over HTTP
## Foreman
alias fs='foreman start'
alias fsp='bundle exec foreman start -f Procfile'
## Brew services
alias bws='brew services list'

# Dev
alias s='subl'
# alias unused='git ctags; cat ./.git/tags | unused'

## Maintenance
alias bw='brew'
alias brew_maintenance='bw doctor; bw update; bw upgrade --cask; bw upgrade; bw cleanup -s; rm -rf "$(brew --cache)"; brewfile'
alias brewfile='(brew_bundle_dump; brew_bundle cleanup --force; brew_bundle check; brew_bundle; brew_bundle_dump)'
alias brew_bundle='bw bundle --no-lock --file=~/dotfiles$ENV_SUFFIX/tools/Brewfile'
alias brew_bundle_dump='brew_bundle dump --force --describe'
alias update='sudo softwareupdate -ia; gem update --system; brew_maintenance'
alias freedisk='diskutil secureErase freespace 0 /' # Afterwards: Reboot; Disk Utility "First Aid"
alias diskusage='ncdu --color dark -rr -x'
# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
# Finally, clear download history from quarantine. https://mths.be/bum
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

# Tools
alias wifi='wifi-password'
alias esen='trans es:en'
alias enes='trans en:es'
alias def='trans -d'
alias pu='paste_unindented'
alias sys='neofetch'
# See https://superuser.com/questions/763071/show-whitespace-characters-in-printout
alias whitespace="sed 's/ /·/g;s/\t/￫/g;s/\r/§/g;s/$/¶/g'"
alias cmds="sed 's/|/\n/g' ~/.bash_history | awk '{CMD[\$1]++;count++;}END { for (a in CMD)print CMD[a] \" \" CMD[a]/count*100 \"% \" a;}' | grep -v \"./\" | column -c3 -s \" \" -t | sort -nr | nl |  head -n50"

## Youtube-dl
alias yt='youtube-dl'
alias yta='yt -f 140 -o "~/Downloads/music/%(title)s.%(ext)s" '
alias ytv='yt -f 22 -o "~/Downloads/video/%(title)s.%(ext)s" '
alias ytvp='yt -f 22 -o "~/Downloads/video/%(title)s.%(ext)s" --cookies ~/Downloads/video/cookies.txt'
alias ytf='yt -F'

# Tmux
alias t=tmux
alias tl='t ls'
alias tn='t new -s'
alias tk='t kill-server'
alias td='t detach'
alias ta='t attach'
alias tsm='~/tmux/scripts/sessions_menu'
# alias ts='tmux display-popup -E "tmux list-sessions | sed -E \'s/:.*$//\' | grep -v \"^$(tmux display-message -p \'#S\')\$\" | fzf --reverse | xargs tmux switch-client -t"'
