#!/usr/bin/env bash

# Apps
## Fzf
[[ -r ~/.fzf.bash ]] && source ~/.fzf.bash;

if [[ "$(/usr/bin/uname -s)" == "Darwin" ]]; then # Distinguish between macos and linux
  # On Intel macOS, homebrew uses folder /usr/local
  HOMEBREW_PREFIX="/usr/local"
  if [[ "$(/usr/bin/uname -m)" == "arm64" ]]; then # Distinguish between M1 and Intel macbooks
    # On ARM (M1) macOS, homebrew uses folder /opt/homebrew
    HOMEBREW_PREFIX="/opt/homebrew"
  fi
elif [[ "$(/usr/bin/uname -s)" == "Linux" ]]; then # Distinguish between macos and linux
  HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
else
  echo "Is this a reebok or a nike?"
fi

### Avoid curl issues
export PATH="$HOMEBREW_PREFIX/opt/curl/bin:$PATH"
export LDFLAGS="-L$HOMEBREW_PREFIX/opt/curl/lib"
export CPPFLAGS="-I$HOMEBREW_PREFIX/opt/curl/include"

## Add Homebrew’s binaries to PATH
export PATH="$HOMEBREW_PREFIX/bin:$PATH"
export PATH="$HOMEBREW_PREFIX/sbin:$PATH"
eval "$($HOMEBREW_PREFIX/bin/brew shellenv)"

## Ruby's rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES # Solve issue with NSCF in macos

## Config sublimetext as default editor
export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"
export EDITOR="subl -w"

## Colorize man pages with bat
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

## FNM Node version manager
eval "$(fnm env --use-on-cd)"

## Python for some node stuff
export PATH="$HOMEBREW_PREFIX/opt/python@3.10/libexec/bin:$PATH"

# Openssl compilation flags
export PATH="$HOMEBREW_PREFIX/opt/openssl@1.1/bin:$PATH"
export LDFLAGS="-L$HOMEBREW_PREFIX/opt/openssl@1.1/lib"
export CPPFLAGS="-I$HOMEBREW_PREFIX/opt/openssl@1.1/include"
export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/opt/openssl@1.1/lib/pkgconfig"

# Postgresql
export PATH="$HOMEBREW_PREFIX/opt/libpq/bin:$PATH"
export LDFLAGS="-L$HOMEBREW_PREFIX/opt/libpq/lib"
export CPPFLAGS="-I$HOMEBREW_PREFIX/opt/libpq/include"
export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/opt/libpq/lib/pkgconfig"

## Imagemagick@6
export PATH="$PATH:$HOMEBREW_PREFIX/opt/imagemagick@6/bin"
export LDFLAGS="-L$HOMEBREW_PREFIX/opt/imagemagick@6/lib"
export CPPFLAGS="-I$HOMEBREW_PREFIX/opt/imagemagick@6/include"
export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/opt/imagemagick@6/lib/pkgconfig"

### Overwrite macos old sqlite3
export PATH="$HOMEBREW_PREFIXopt/sqlite/bin:$PATH"

### Docker desktop app
export PATH="$HOME/.docker/bin:$PATH"
