#!/usr/bin/env bash

# Apps
## Fzf
[[ -r ~/.fzf.bash ]] && source ~/.fzf.bash;

## Avoid curl issues
export PATH="/opt/homebrew/opt/curl/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/curl/lib"
export CPPFLAGS="-I/opt/homebrew/opt/curl/include"

## Add Homebrew’s sbin to PATH
export PATH="/opt/homebrew/sbin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
eval "$(/opt/homebrew/bin/brew shellenv)"

## Ruby's rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES # Solve issue with NSCF

## Config sublimetext as default editor
export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"
export EDITOR="subl -w"

## Colorize man pages with bat
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

## FNM Node version manager
eval "$(fnm env --use-on-cd)"

## Python for some node stuff
export PATH="$HOMEBREW_PREFIX/opt/python@3.10/libexec/bin:$PATH"
