#!/usr/bin/env bash
# https://github.com/thoughtbot/dotfiles/blob/master/git_template/hooks/ctags
set -e

PATH="/opt/homebrew/bin:$PATH"
dir="$(git rev-parse --git-dir)"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  "${CTAGS:-ctags}" --tag-relative=yes -L - -f"$dir/$$.tags" --languages=ruby
mv "$dir/$$.tags" "$dir/tags"
